### ISSUE TITLE
Is it possible change to enum?

### ISSUE THREAD

**Issue by SparkyCloudy** [Made-Budhi/Broom-project#51]
https://github.com/Made-Budhi/Broom-project/blob/7450fe62f9902562bc4d4d6ee35b60fa3fb347d2/db_broom.sql#L110

kalau dipikir, ini ada baiknya jadi enum karena valuenya itu aja, atau ada alasan yang lebih mendasar kenapa harus dibuatin tabel baru lagi?

https://github.com/Made-Budhi/Broom-project/blob/7450fe62f9902562bc4d4d6ee35b60fa3fb347d2/db_broom.sql#L122

kalau dibuat dibawah ini, jadi field, bukannya lebih effisien?

**Comment by SparkyCloudy** [comment]
@Made-Budhi

**Comment by Made-Budhi** [comment]
Alasan aku pas itu bikin table baru karena saran Dari bu Incip yang nyuruh message nya sekalian taruh di database. Tapi ternyata aku putusin buat message nya lebih dinamis jadi message nya langsung di code nya aja.

Jadi kalau mau type di Notification dijadiin enum dan Notification _Master dihapus itu boleh asalkan dokumentasi nya wajib setiap nambah type Notification yang baru.

**Comment by SparkyCloudy** [comment]
oke, nanti branch terpisah deh
